// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.7, generator: @autorest/go@4.0.0-preview.72)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package cosmos_db

// CassandraResourcesClientCreateUpdateCassandraKeyspaceResponse contains the response from method CassandraResourcesClient.BeginCreateUpdateCassandraKeyspace.
type CassandraResourcesClientCreateUpdateCassandraKeyspaceResponse struct {
// An Azure Cosmos DB Cassandra keyspace.
	CassandraKeyspaceGetResults
}

// CassandraResourcesClientCreateUpdateCassandraTableResponse contains the response from method CassandraResourcesClient.BeginCreateUpdateCassandraTable.
type CassandraResourcesClientCreateUpdateCassandraTableResponse struct {
// An Azure Cosmos DB Cassandra table.
	CassandraTableGetResults
}

// CassandraResourcesClientDeleteCassandraKeyspaceResponse contains the response from method CassandraResourcesClient.BeginDeleteCassandraKeyspace.
type CassandraResourcesClientDeleteCassandraKeyspaceResponse struct {
	// placeholder for future response values
}

// CassandraResourcesClientDeleteCassandraTableResponse contains the response from method CassandraResourcesClient.BeginDeleteCassandraTable.
type CassandraResourcesClientDeleteCassandraTableResponse struct {
	// placeholder for future response values
}

// CassandraResourcesClientGetCassandraKeyspaceResponse contains the response from method CassandraResourcesClient.GetCassandraKeyspace.
type CassandraResourcesClientGetCassandraKeyspaceResponse struct {
// An Azure Cosmos DB Cassandra keyspace.
	CassandraKeyspaceGetResults
}

// CassandraResourcesClientGetCassandraKeyspaceThroughputResponse contains the response from method CassandraResourcesClient.GetCassandraKeyspaceThroughput.
type CassandraResourcesClientGetCassandraKeyspaceThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// CassandraResourcesClientGetCassandraTableResponse contains the response from method CassandraResourcesClient.GetCassandraTable.
type CassandraResourcesClientGetCassandraTableResponse struct {
// An Azure Cosmos DB Cassandra table.
	CassandraTableGetResults
}

// CassandraResourcesClientGetCassandraTableThroughputResponse contains the response from method CassandraResourcesClient.GetCassandraTableThroughput.
type CassandraResourcesClientGetCassandraTableThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// CassandraResourcesClientListCassandraKeyspacesResponse contains the response from method CassandraResourcesClient.NewListCassandraKeyspacesPager.
type CassandraResourcesClientListCassandraKeyspacesResponse struct {
// The List operation response, that contains the Cassandra keyspaces and their properties.
	CassandraKeyspaceListResult
}

// CassandraResourcesClientListCassandraTablesResponse contains the response from method CassandraResourcesClient.NewListCassandraTablesPager.
type CassandraResourcesClientListCassandraTablesResponse struct {
// The List operation response, that contains the Cassandra tables and their properties.
	CassandraTableListResult
}

// CassandraResourcesClientMigrateCassandraKeyspaceToAutoscaleResponse contains the response from method CassandraResourcesClient.BeginMigrateCassandraKeyspaceToAutoscale.
type CassandraResourcesClientMigrateCassandraKeyspaceToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// CassandraResourcesClientMigrateCassandraKeyspaceToManualThroughputResponse contains the response from method CassandraResourcesClient.BeginMigrateCassandraKeyspaceToManualThroughput.
type CassandraResourcesClientMigrateCassandraKeyspaceToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// CassandraResourcesClientMigrateCassandraTableToAutoscaleResponse contains the response from method CassandraResourcesClient.BeginMigrateCassandraTableToAutoscale.
type CassandraResourcesClientMigrateCassandraTableToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// CassandraResourcesClientMigrateCassandraTableToManualThroughputResponse contains the response from method CassandraResourcesClient.BeginMigrateCassandraTableToManualThroughput.
type CassandraResourcesClientMigrateCassandraTableToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// CassandraResourcesClientUpdateCassandraKeyspaceThroughputResponse contains the response from method CassandraResourcesClient.BeginUpdateCassandraKeyspaceThroughput.
type CassandraResourcesClientUpdateCassandraKeyspaceThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// CassandraResourcesClientUpdateCassandraTableThroughputResponse contains the response from method CassandraResourcesClient.BeginUpdateCassandraTableThroughput.
type CassandraResourcesClientUpdateCassandraTableThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// CollectionClientListMetricDefinitionsResponse contains the response from method CollectionClient.NewListMetricDefinitionsPager.
type CollectionClientListMetricDefinitionsResponse struct {
// The response to a list metric definitions request.
	MetricDefinitionsListResult
}

// CollectionClientListMetricsResponse contains the response from method CollectionClient.NewListMetricsPager.
type CollectionClientListMetricsResponse struct {
// The response to a list metrics request.
	MetricListResult
}

// CollectionClientListUsagesResponse contains the response from method CollectionClient.NewListUsagesPager.
type CollectionClientListUsagesResponse struct {
// The response to a list usage request.
	UsagesResult
}

// CollectionPartitionClientListMetricsResponse contains the response from method CollectionPartitionClient.NewListMetricsPager.
type CollectionPartitionClientListMetricsResponse struct {
// The response to a list partition metrics request.
	PartitionMetricListResult
}

// CollectionPartitionClientListUsagesResponse contains the response from method CollectionPartitionClient.NewListUsagesPager.
type CollectionPartitionClientListUsagesResponse struct {
// The response to a list partition level usage request.
	PartitionUsagesResult
}

// CollectionPartitionRegionClientListMetricsResponse contains the response from method CollectionPartitionRegionClient.NewListMetricsPager.
type CollectionPartitionRegionClientListMetricsResponse struct {
// The response to a list partition metrics request.
	PartitionMetricListResult
}

// CollectionRegionClientListMetricsResponse contains the response from method CollectionRegionClient.NewListMetricsPager.
type CollectionRegionClientListMetricsResponse struct {
// The response to a list metrics request.
	MetricListResult
}

// DatabaseAccountRegionClientListMetricsResponse contains the response from method DatabaseAccountRegionClient.NewListMetricsPager.
type DatabaseAccountRegionClientListMetricsResponse struct {
// The response to a list metrics request.
	MetricListResult
}

// DatabaseAccountsClientCheckNameExistsResponse contains the response from method DatabaseAccountsClient.CheckNameExists.
type DatabaseAccountsClientCheckNameExistsResponse struct {
	// placeholder for future response values
}

// DatabaseAccountsClientCreateOrUpdateResponse contains the response from method DatabaseAccountsClient.BeginCreateOrUpdate.
type DatabaseAccountsClientCreateOrUpdateResponse struct {
// An Azure Cosmos DB database account.
	DatabaseAccountGetResults
}

// DatabaseAccountsClientDeleteResponse contains the response from method DatabaseAccountsClient.BeginDelete.
type DatabaseAccountsClientDeleteResponse struct {
	// placeholder for future response values
}

// DatabaseAccountsClientFailoverPriorityChangeResponse contains the response from method DatabaseAccountsClient.BeginFailoverPriorityChange.
type DatabaseAccountsClientFailoverPriorityChangeResponse struct {
	// placeholder for future response values
}

// DatabaseAccountsClientGetReadOnlyKeysResponse contains the response from method DatabaseAccountsClient.GetReadOnlyKeys.
type DatabaseAccountsClientGetReadOnlyKeysResponse struct {
// The read-only access keys for the given database account.
	DatabaseAccountListReadOnlyKeysResult
}

// DatabaseAccountsClientGetResponse contains the response from method DatabaseAccountsClient.Get.
type DatabaseAccountsClientGetResponse struct {
// An Azure Cosmos DB database account.
	DatabaseAccountGetResults
}

// DatabaseAccountsClientListByResourceGroupResponse contains the response from method DatabaseAccountsClient.NewListByResourceGroupPager.
type DatabaseAccountsClientListByResourceGroupResponse struct {
// The List operation response, that contains the database accounts and their properties.
	DatabaseAccountsListResult
}

// DatabaseAccountsClientListConnectionStringsResponse contains the response from method DatabaseAccountsClient.ListConnectionStrings.
type DatabaseAccountsClientListConnectionStringsResponse struct {
// The connection strings for the given database account.
	DatabaseAccountListConnectionStringsResult
}

// DatabaseAccountsClientListKeysResponse contains the response from method DatabaseAccountsClient.ListKeys.
type DatabaseAccountsClientListKeysResponse struct {
// The access keys for the given database account.
	DatabaseAccountListKeysResult
}

// DatabaseAccountsClientListMetricDefinitionsResponse contains the response from method DatabaseAccountsClient.NewListMetricDefinitionsPager.
type DatabaseAccountsClientListMetricDefinitionsResponse struct {
// The response to a list metric definitions request.
	MetricDefinitionsListResult
}

// DatabaseAccountsClientListMetricsResponse contains the response from method DatabaseAccountsClient.NewListMetricsPager.
type DatabaseAccountsClientListMetricsResponse struct {
// The response to a list metrics request.
	MetricListResult
}

// DatabaseAccountsClientListReadOnlyKeysResponse contains the response from method DatabaseAccountsClient.ListReadOnlyKeys.
type DatabaseAccountsClientListReadOnlyKeysResponse struct {
// The read-only access keys for the given database account.
	DatabaseAccountListReadOnlyKeysResult
}

// DatabaseAccountsClientListResponse contains the response from method DatabaseAccountsClient.NewListPager.
type DatabaseAccountsClientListResponse struct {
// The List operation response, that contains the database accounts and their properties.
	DatabaseAccountsListResult
}

// DatabaseAccountsClientListUsagesResponse contains the response from method DatabaseAccountsClient.NewListUsagesPager.
type DatabaseAccountsClientListUsagesResponse struct {
// The response to a list usage request.
	UsagesResult
}

// DatabaseAccountsClientOfflineRegionResponse contains the response from method DatabaseAccountsClient.BeginOfflineRegion.
type DatabaseAccountsClientOfflineRegionResponse struct {
	// placeholder for future response values
}

// DatabaseAccountsClientOnlineRegionResponse contains the response from method DatabaseAccountsClient.BeginOnlineRegion.
type DatabaseAccountsClientOnlineRegionResponse struct {
	// placeholder for future response values
}

// DatabaseAccountsClientRegenerateKeyResponse contains the response from method DatabaseAccountsClient.BeginRegenerateKey.
type DatabaseAccountsClientRegenerateKeyResponse struct {
	// placeholder for future response values
}

// DatabaseAccountsClientUpdateResponse contains the response from method DatabaseAccountsClient.BeginUpdate.
type DatabaseAccountsClientUpdateResponse struct {
// An Azure Cosmos DB database account.
	DatabaseAccountGetResults
}

// DatabaseClientListMetricDefinitionsResponse contains the response from method DatabaseClient.NewListMetricDefinitionsPager.
type DatabaseClientListMetricDefinitionsResponse struct {
// The response to a list metric definitions request.
	MetricDefinitionsListResult
}

// DatabaseClientListMetricsResponse contains the response from method DatabaseClient.NewListMetricsPager.
type DatabaseClientListMetricsResponse struct {
// The response to a list metrics request.
	MetricListResult
}

// DatabaseClientListUsagesResponse contains the response from method DatabaseClient.NewListUsagesPager.
type DatabaseClientListUsagesResponse struct {
// The response to a list usage request.
	UsagesResult
}

// GremlinResourcesClientCreateUpdateGremlinDatabaseResponse contains the response from method GremlinResourcesClient.BeginCreateUpdateGremlinDatabase.
type GremlinResourcesClientCreateUpdateGremlinDatabaseResponse struct {
// An Azure Cosmos DB Gremlin database.
	GremlinDatabaseGetResults
}

// GremlinResourcesClientCreateUpdateGremlinGraphResponse contains the response from method GremlinResourcesClient.BeginCreateUpdateGremlinGraph.
type GremlinResourcesClientCreateUpdateGremlinGraphResponse struct {
// An Azure Cosmos DB Gremlin graph.
	GremlinGraphGetResults
}

// GremlinResourcesClientDeleteGremlinDatabaseResponse contains the response from method GremlinResourcesClient.BeginDeleteGremlinDatabase.
type GremlinResourcesClientDeleteGremlinDatabaseResponse struct {
	// placeholder for future response values
}

// GremlinResourcesClientDeleteGremlinGraphResponse contains the response from method GremlinResourcesClient.BeginDeleteGremlinGraph.
type GremlinResourcesClientDeleteGremlinGraphResponse struct {
	// placeholder for future response values
}

// GremlinResourcesClientGetGremlinDatabaseResponse contains the response from method GremlinResourcesClient.GetGremlinDatabase.
type GremlinResourcesClientGetGremlinDatabaseResponse struct {
// An Azure Cosmos DB Gremlin database.
	GremlinDatabaseGetResults
}

// GremlinResourcesClientGetGremlinDatabaseThroughputResponse contains the response from method GremlinResourcesClient.GetGremlinDatabaseThroughput.
type GremlinResourcesClientGetGremlinDatabaseThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// GremlinResourcesClientGetGremlinGraphResponse contains the response from method GremlinResourcesClient.GetGremlinGraph.
type GremlinResourcesClientGetGremlinGraphResponse struct {
// An Azure Cosmos DB Gremlin graph.
	GremlinGraphGetResults
}

// GremlinResourcesClientGetGremlinGraphThroughputResponse contains the response from method GremlinResourcesClient.GetGremlinGraphThroughput.
type GremlinResourcesClientGetGremlinGraphThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// GremlinResourcesClientListGremlinDatabasesResponse contains the response from method GremlinResourcesClient.NewListGremlinDatabasesPager.
type GremlinResourcesClientListGremlinDatabasesResponse struct {
// The List operation response, that contains the Gremlin databases and their properties.
	GremlinDatabaseListResult
}

// GremlinResourcesClientListGremlinGraphsResponse contains the response from method GremlinResourcesClient.NewListGremlinGraphsPager.
type GremlinResourcesClientListGremlinGraphsResponse struct {
// The List operation response, that contains the graphs and their properties.
	GremlinGraphListResult
}

// GremlinResourcesClientMigrateGremlinDatabaseToAutoscaleResponse contains the response from method GremlinResourcesClient.BeginMigrateGremlinDatabaseToAutoscale.
type GremlinResourcesClientMigrateGremlinDatabaseToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// GremlinResourcesClientMigrateGremlinDatabaseToManualThroughputResponse contains the response from method GremlinResourcesClient.BeginMigrateGremlinDatabaseToManualThroughput.
type GremlinResourcesClientMigrateGremlinDatabaseToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// GremlinResourcesClientMigrateGremlinGraphToAutoscaleResponse contains the response from method GremlinResourcesClient.BeginMigrateGremlinGraphToAutoscale.
type GremlinResourcesClientMigrateGremlinGraphToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// GremlinResourcesClientMigrateGremlinGraphToManualThroughputResponse contains the response from method GremlinResourcesClient.BeginMigrateGremlinGraphToManualThroughput.
type GremlinResourcesClientMigrateGremlinGraphToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// GremlinResourcesClientUpdateGremlinDatabaseThroughputResponse contains the response from method GremlinResourcesClient.BeginUpdateGremlinDatabaseThroughput.
type GremlinResourcesClientUpdateGremlinDatabaseThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// GremlinResourcesClientUpdateGremlinGraphThroughputResponse contains the response from method GremlinResourcesClient.BeginUpdateGremlinGraphThroughput.
type GremlinResourcesClientUpdateGremlinGraphThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// LocationsClientGetResponse contains the response from method LocationsClient.Get.
type LocationsClientGetResponse struct {
// Cosmos DB location get result
	LocationGetResult
}

// LocationsClientListResponse contains the response from method LocationsClient.NewListPager.
type LocationsClientListResponse struct {
// The List operation response, that contains Cosmos DB locations and their properties.
	LocationListResult
}

// MongoDBResourcesClientCreateUpdateMongoDBCollectionResponse contains the response from method MongoDBResourcesClient.BeginCreateUpdateMongoDBCollection.
type MongoDBResourcesClientCreateUpdateMongoDBCollectionResponse struct {
// An Azure Cosmos DB MongoDB collection.
	MongoDBCollectionGetResults
}

// MongoDBResourcesClientCreateUpdateMongoDBDatabaseResponse contains the response from method MongoDBResourcesClient.BeginCreateUpdateMongoDBDatabase.
type MongoDBResourcesClientCreateUpdateMongoDBDatabaseResponse struct {
// An Azure Cosmos DB MongoDB database.
	MongoDBDatabaseGetResults
}

// MongoDBResourcesClientDeleteMongoDBCollectionResponse contains the response from method MongoDBResourcesClient.BeginDeleteMongoDBCollection.
type MongoDBResourcesClientDeleteMongoDBCollectionResponse struct {
	// placeholder for future response values
}

// MongoDBResourcesClientDeleteMongoDBDatabaseResponse contains the response from method MongoDBResourcesClient.BeginDeleteMongoDBDatabase.
type MongoDBResourcesClientDeleteMongoDBDatabaseResponse struct {
	// placeholder for future response values
}

// MongoDBResourcesClientGetMongoDBCollectionResponse contains the response from method MongoDBResourcesClient.GetMongoDBCollection.
type MongoDBResourcesClientGetMongoDBCollectionResponse struct {
// An Azure Cosmos DB MongoDB collection.
	MongoDBCollectionGetResults
}

// MongoDBResourcesClientGetMongoDBCollectionThroughputResponse contains the response from method MongoDBResourcesClient.GetMongoDBCollectionThroughput.
type MongoDBResourcesClientGetMongoDBCollectionThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// MongoDBResourcesClientGetMongoDBDatabaseResponse contains the response from method MongoDBResourcesClient.GetMongoDBDatabase.
type MongoDBResourcesClientGetMongoDBDatabaseResponse struct {
// An Azure Cosmos DB MongoDB database.
	MongoDBDatabaseGetResults
}

// MongoDBResourcesClientGetMongoDBDatabaseThroughputResponse contains the response from method MongoDBResourcesClient.GetMongoDBDatabaseThroughput.
type MongoDBResourcesClientGetMongoDBDatabaseThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// MongoDBResourcesClientListMongoDBCollectionsResponse contains the response from method MongoDBResourcesClient.NewListMongoDBCollectionsPager.
type MongoDBResourcesClientListMongoDBCollectionsResponse struct {
// The List operation response, that contains the MongoDB collections and their properties.
	MongoDBCollectionListResult
}

// MongoDBResourcesClientListMongoDBDatabasesResponse contains the response from method MongoDBResourcesClient.NewListMongoDBDatabasesPager.
type MongoDBResourcesClientListMongoDBDatabasesResponse struct {
// The List operation response, that contains the MongoDB databases and their properties.
	MongoDBDatabaseListResult
}

// MongoDBResourcesClientMigrateMongoDBCollectionToAutoscaleResponse contains the response from method MongoDBResourcesClient.BeginMigrateMongoDBCollectionToAutoscale.
type MongoDBResourcesClientMigrateMongoDBCollectionToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// MongoDBResourcesClientMigrateMongoDBCollectionToManualThroughputResponse contains the response from method MongoDBResourcesClient.BeginMigrateMongoDBCollectionToManualThroughput.
type MongoDBResourcesClientMigrateMongoDBCollectionToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// MongoDBResourcesClientMigrateMongoDBDatabaseToAutoscaleResponse contains the response from method MongoDBResourcesClient.BeginMigrateMongoDBDatabaseToAutoscale.
type MongoDBResourcesClientMigrateMongoDBDatabaseToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// MongoDBResourcesClientMigrateMongoDBDatabaseToManualThroughputResponse contains the response from method MongoDBResourcesClient.BeginMigrateMongoDBDatabaseToManualThroughput.
type MongoDBResourcesClientMigrateMongoDBDatabaseToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// MongoDBResourcesClientUpdateMongoDBCollectionThroughputResponse contains the response from method MongoDBResourcesClient.BeginUpdateMongoDBCollectionThroughput.
type MongoDBResourcesClientUpdateMongoDBCollectionThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// MongoDBResourcesClientUpdateMongoDBDatabaseThroughputResponse contains the response from method MongoDBResourcesClient.BeginUpdateMongoDBDatabaseThroughput.
type MongoDBResourcesClientUpdateMongoDBDatabaseThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// OperationsClientListResponse contains the response from method OperationsClient.NewListPager.
type OperationsClientListResponse struct {
// Result of the request to list Resource Provider operations. It contains a list of operations and a URL link to get the
// next set of results.
	OperationListResult
}

// PartitionKeyRangeIDClientListMetricsResponse contains the response from method PartitionKeyRangeIDClient.NewListMetricsPager.
type PartitionKeyRangeIDClientListMetricsResponse struct {
// The response to a list partition metrics request.
	PartitionMetricListResult
}

// PartitionKeyRangeIDRegionClientListMetricsResponse contains the response from method PartitionKeyRangeIDRegionClient.NewListMetricsPager.
type PartitionKeyRangeIDRegionClientListMetricsResponse struct {
// The response to a list partition metrics request.
	PartitionMetricListResult
}

// PercentileClientListMetricsResponse contains the response from method PercentileClient.NewListMetricsPager.
type PercentileClientListMetricsResponse struct {
// The response to a list percentile metrics request.
	PercentileMetricListResult
}

// PercentileSourceTargetClientListMetricsResponse contains the response from method PercentileSourceTargetClient.NewListMetricsPager.
type PercentileSourceTargetClientListMetricsResponse struct {
// The response to a list percentile metrics request.
	PercentileMetricListResult
}

// PercentileTargetClientListMetricsResponse contains the response from method PercentileTargetClient.NewListMetricsPager.
type PercentileTargetClientListMetricsResponse struct {
// The response to a list percentile metrics request.
	PercentileMetricListResult
}

// SQLResourcesClientCreateUpdateClientEncryptionKeyResponse contains the response from method SQLResourcesClient.BeginCreateUpdateClientEncryptionKey.
type SQLResourcesClientCreateUpdateClientEncryptionKeyResponse struct {
// Client Encryption Key.
	ClientEncryptionKeyGetResults
}

// SQLResourcesClientCreateUpdateSQLContainerResponse contains the response from method SQLResourcesClient.BeginCreateUpdateSQLContainer.
type SQLResourcesClientCreateUpdateSQLContainerResponse struct {
// An Azure Cosmos DB container.
	SQLContainerGetResults
}

// SQLResourcesClientCreateUpdateSQLDatabaseResponse contains the response from method SQLResourcesClient.BeginCreateUpdateSQLDatabase.
type SQLResourcesClientCreateUpdateSQLDatabaseResponse struct {
// An Azure Cosmos DB SQL database.
	SQLDatabaseGetResults
}

// SQLResourcesClientCreateUpdateSQLStoredProcedureResponse contains the response from method SQLResourcesClient.BeginCreateUpdateSQLStoredProcedure.
type SQLResourcesClientCreateUpdateSQLStoredProcedureResponse struct {
// An Azure Cosmos DB storedProcedure.
	SQLStoredProcedureGetResults
}

// SQLResourcesClientCreateUpdateSQLTriggerResponse contains the response from method SQLResourcesClient.BeginCreateUpdateSQLTrigger.
type SQLResourcesClientCreateUpdateSQLTriggerResponse struct {
// An Azure Cosmos DB trigger.
	SQLTriggerGetResults
}

// SQLResourcesClientCreateUpdateSQLUserDefinedFunctionResponse contains the response from method SQLResourcesClient.BeginCreateUpdateSQLUserDefinedFunction.
type SQLResourcesClientCreateUpdateSQLUserDefinedFunctionResponse struct {
// An Azure Cosmos DB userDefinedFunction.
	SQLUserDefinedFunctionGetResults
}

// SQLResourcesClientDeleteSQLContainerResponse contains the response from method SQLResourcesClient.BeginDeleteSQLContainer.
type SQLResourcesClientDeleteSQLContainerResponse struct {
	// placeholder for future response values
}

// SQLResourcesClientDeleteSQLDatabaseResponse contains the response from method SQLResourcesClient.BeginDeleteSQLDatabase.
type SQLResourcesClientDeleteSQLDatabaseResponse struct {
	// placeholder for future response values
}

// SQLResourcesClientDeleteSQLStoredProcedureResponse contains the response from method SQLResourcesClient.BeginDeleteSQLStoredProcedure.
type SQLResourcesClientDeleteSQLStoredProcedureResponse struct {
	// placeholder for future response values
}

// SQLResourcesClientDeleteSQLTriggerResponse contains the response from method SQLResourcesClient.BeginDeleteSQLTrigger.
type SQLResourcesClientDeleteSQLTriggerResponse struct {
	// placeholder for future response values
}

// SQLResourcesClientDeleteSQLUserDefinedFunctionResponse contains the response from method SQLResourcesClient.BeginDeleteSQLUserDefinedFunction.
type SQLResourcesClientDeleteSQLUserDefinedFunctionResponse struct {
	// placeholder for future response values
}

// SQLResourcesClientGetClientEncryptionKeyResponse contains the response from method SQLResourcesClient.GetClientEncryptionKey.
type SQLResourcesClientGetClientEncryptionKeyResponse struct {
// Client Encryption Key.
	ClientEncryptionKeyGetResults
}

// SQLResourcesClientGetSQLContainerResponse contains the response from method SQLResourcesClient.GetSQLContainer.
type SQLResourcesClientGetSQLContainerResponse struct {
// An Azure Cosmos DB container.
	SQLContainerGetResults
}

// SQLResourcesClientGetSQLContainerThroughputResponse contains the response from method SQLResourcesClient.GetSQLContainerThroughput.
type SQLResourcesClientGetSQLContainerThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// SQLResourcesClientGetSQLDatabaseResponse contains the response from method SQLResourcesClient.GetSQLDatabase.
type SQLResourcesClientGetSQLDatabaseResponse struct {
// An Azure Cosmos DB SQL database.
	SQLDatabaseGetResults
}

// SQLResourcesClientGetSQLDatabaseThroughputResponse contains the response from method SQLResourcesClient.GetSQLDatabaseThroughput.
type SQLResourcesClientGetSQLDatabaseThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// SQLResourcesClientGetSQLStoredProcedureResponse contains the response from method SQLResourcesClient.GetSQLStoredProcedure.
type SQLResourcesClientGetSQLStoredProcedureResponse struct {
// An Azure Cosmos DB storedProcedure.
	SQLStoredProcedureGetResults
}

// SQLResourcesClientGetSQLTriggerResponse contains the response from method SQLResourcesClient.GetSQLTrigger.
type SQLResourcesClientGetSQLTriggerResponse struct {
// An Azure Cosmos DB trigger.
	SQLTriggerGetResults
}

// SQLResourcesClientGetSQLUserDefinedFunctionResponse contains the response from method SQLResourcesClient.GetSQLUserDefinedFunction.
type SQLResourcesClientGetSQLUserDefinedFunctionResponse struct {
// An Azure Cosmos DB userDefinedFunction.
	SQLUserDefinedFunctionGetResults
}

// SQLResourcesClientListClientEncryptionKeysResponse contains the response from method SQLResourcesClient.NewListClientEncryptionKeysPager.
type SQLResourcesClientListClientEncryptionKeysResponse struct {
// The List operation response, that contains the client encryption keys and their properties.
	ClientEncryptionKeysListResult
}

// SQLResourcesClientListSQLContainersResponse contains the response from method SQLResourcesClient.NewListSQLContainersPager.
type SQLResourcesClientListSQLContainersResponse struct {
// The List operation response, that contains the containers and their properties.
	SQLContainerListResult
}

// SQLResourcesClientListSQLDatabasesResponse contains the response from method SQLResourcesClient.NewListSQLDatabasesPager.
type SQLResourcesClientListSQLDatabasesResponse struct {
// The List operation response, that contains the SQL databases and their properties.
	SQLDatabaseListResult
}

// SQLResourcesClientListSQLStoredProceduresResponse contains the response from method SQLResourcesClient.NewListSQLStoredProceduresPager.
type SQLResourcesClientListSQLStoredProceduresResponse struct {
// The List operation response, that contains the storedProcedures and their properties.
	SQLStoredProcedureListResult
}

// SQLResourcesClientListSQLTriggersResponse contains the response from method SQLResourcesClient.NewListSQLTriggersPager.
type SQLResourcesClientListSQLTriggersResponse struct {
// The List operation response, that contains the triggers and their properties.
	SQLTriggerListResult
}

// SQLResourcesClientListSQLUserDefinedFunctionsResponse contains the response from method SQLResourcesClient.NewListSQLUserDefinedFunctionsPager.
type SQLResourcesClientListSQLUserDefinedFunctionsResponse struct {
// The List operation response, that contains the userDefinedFunctions and their properties.
	SQLUserDefinedFunctionListResult
}

// SQLResourcesClientMigrateSQLContainerToAutoscaleResponse contains the response from method SQLResourcesClient.BeginMigrateSQLContainerToAutoscale.
type SQLResourcesClientMigrateSQLContainerToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// SQLResourcesClientMigrateSQLContainerToManualThroughputResponse contains the response from method SQLResourcesClient.BeginMigrateSQLContainerToManualThroughput.
type SQLResourcesClientMigrateSQLContainerToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// SQLResourcesClientMigrateSQLDatabaseToAutoscaleResponse contains the response from method SQLResourcesClient.BeginMigrateSQLDatabaseToAutoscale.
type SQLResourcesClientMigrateSQLDatabaseToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// SQLResourcesClientMigrateSQLDatabaseToManualThroughputResponse contains the response from method SQLResourcesClient.BeginMigrateSQLDatabaseToManualThroughput.
type SQLResourcesClientMigrateSQLDatabaseToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// SQLResourcesClientUpdateSQLContainerThroughputResponse contains the response from method SQLResourcesClient.BeginUpdateSQLContainerThroughput.
type SQLResourcesClientUpdateSQLContainerThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// SQLResourcesClientUpdateSQLDatabaseThroughputResponse contains the response from method SQLResourcesClient.BeginUpdateSQLDatabaseThroughput.
type SQLResourcesClientUpdateSQLDatabaseThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// TableResourcesClientCreateUpdateTableResponse contains the response from method TableResourcesClient.BeginCreateUpdateTable.
type TableResourcesClientCreateUpdateTableResponse struct {
// An Azure Cosmos DB Table.
	TableGetResults
}

// TableResourcesClientDeleteTableResponse contains the response from method TableResourcesClient.BeginDeleteTable.
type TableResourcesClientDeleteTableResponse struct {
	// placeholder for future response values
}

// TableResourcesClientGetTableResponse contains the response from method TableResourcesClient.GetTable.
type TableResourcesClientGetTableResponse struct {
// An Azure Cosmos DB Table.
	TableGetResults
}

// TableResourcesClientGetTableThroughputResponse contains the response from method TableResourcesClient.GetTableThroughput.
type TableResourcesClientGetTableThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// TableResourcesClientListTablesResponse contains the response from method TableResourcesClient.NewListTablesPager.
type TableResourcesClientListTablesResponse struct {
// The List operation response, that contains the Table and their properties.
	TableListResult
}

// TableResourcesClientMigrateTableToAutoscaleResponse contains the response from method TableResourcesClient.BeginMigrateTableToAutoscale.
type TableResourcesClientMigrateTableToAutoscaleResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// TableResourcesClientMigrateTableToManualThroughputResponse contains the response from method TableResourcesClient.BeginMigrateTableToManualThroughput.
type TableResourcesClientMigrateTableToManualThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

// TableResourcesClientUpdateTableThroughputResponse contains the response from method TableResourcesClient.BeginUpdateTableThroughput.
type TableResourcesClientUpdateTableThroughputResponse struct {
// An Azure Cosmos DB resource throughput.
	ThroughputSettingsGetResults
}

