// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.7, generator: @autorest/go@4.0.0-preview.72)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package storage

// AccountsClientAbortHierarchicalNamespaceMigrationResponse contains the response from method AccountsClient.BeginAbortHierarchicalNamespaceMigration.
type AccountsClientAbortHierarchicalNamespaceMigrationResponse struct {
	// placeholder for future response values
}

// AccountsClientCheckNameAvailabilityResponse contains the response from method AccountsClient.CheckNameAvailability.
type AccountsClientCheckNameAvailabilityResponse struct {
// The CheckNameAvailability operation response.
	CheckNameAvailabilityResult
}

// AccountsClientCreateResponse contains the response from method AccountsClient.BeginCreate.
type AccountsClientCreateResponse struct {
// The storage account.
	Account
}

// AccountsClientCustomerInitiatedMigrationResponse contains the response from method AccountsClient.BeginCustomerInitiatedMigration.
type AccountsClientCustomerInitiatedMigrationResponse struct {
	// placeholder for future response values
}

// AccountsClientDeleteResponse contains the response from method AccountsClient.Delete.
type AccountsClientDeleteResponse struct {
	// placeholder for future response values
}

// AccountsClientFailoverResponse contains the response from method AccountsClient.BeginFailover.
type AccountsClientFailoverResponse struct {
	// placeholder for future response values
}

// AccountsClientGetCustomerInitiatedMigrationResponse contains the response from method AccountsClient.GetCustomerInitiatedMigration.
type AccountsClientGetCustomerInitiatedMigrationResponse struct {
// The parameters or status associated with an ongoing or enqueued storage account migration in order to update its current
// SKU or region.
	AccountMigration
}

// AccountsClientGetPropertiesResponse contains the response from method AccountsClient.GetProperties.
type AccountsClientGetPropertiesResponse struct {
// The storage account.
	Account
}

// AccountsClientHierarchicalNamespaceMigrationResponse contains the response from method AccountsClient.BeginHierarchicalNamespaceMigration.
type AccountsClientHierarchicalNamespaceMigrationResponse struct {
	// placeholder for future response values
}

// AccountsClientListAccountSASResponse contains the response from method AccountsClient.ListAccountSAS.
type AccountsClientListAccountSASResponse struct {
// The List SAS credentials operation response.
	ListAccountSasResponse
}

// AccountsClientListByResourceGroupResponse contains the response from method AccountsClient.NewListByResourceGroupPager.
type AccountsClientListByResourceGroupResponse struct {
// The response from the List Storage Accounts operation.
	AccountListResult
}

// AccountsClientListKeysResponse contains the response from method AccountsClient.ListKeys.
type AccountsClientListKeysResponse struct {
// The response from the ListKeys operation.
	AccountListKeysResult
}

// AccountsClientListResponse contains the response from method AccountsClient.NewListPager.
type AccountsClientListResponse struct {
// The response from the List Storage Accounts operation.
	AccountListResult
}

// AccountsClientListServiceSASResponse contains the response from method AccountsClient.ListServiceSAS.
type AccountsClientListServiceSASResponse struct {
// The List service SAS credentials operation response.
	ListServiceSasResponse
}

// AccountsClientRegenerateKeyResponse contains the response from method AccountsClient.RegenerateKey.
type AccountsClientRegenerateKeyResponse struct {
// The response from the ListKeys operation.
	AccountListKeysResult
}

// AccountsClientRestoreBlobRangesResponse contains the response from method AccountsClient.BeginRestoreBlobRanges.
type AccountsClientRestoreBlobRangesResponse struct {
// Blob restore status.
	BlobRestoreStatus
}

// AccountsClientRevokeUserDelegationKeysResponse contains the response from method AccountsClient.RevokeUserDelegationKeys.
type AccountsClientRevokeUserDelegationKeysResponse struct {
	// placeholder for future response values
}

// AccountsClientUpdateResponse contains the response from method AccountsClient.Update.
type AccountsClientUpdateResponse struct {
// The storage account.
	Account
}

// BlobInventoryPoliciesClientCreateOrUpdateResponse contains the response from method BlobInventoryPoliciesClient.CreateOrUpdate.
type BlobInventoryPoliciesClientCreateOrUpdateResponse struct {
// The storage account blob inventory policy.
	BlobInventoryPolicy
}

// BlobInventoryPoliciesClientDeleteResponse contains the response from method BlobInventoryPoliciesClient.Delete.
type BlobInventoryPoliciesClientDeleteResponse struct {
	// placeholder for future response values
}

// BlobInventoryPoliciesClientGetResponse contains the response from method BlobInventoryPoliciesClient.Get.
type BlobInventoryPoliciesClientGetResponse struct {
// The storage account blob inventory policy.
	BlobInventoryPolicy
}

// BlobInventoryPoliciesClientListResponse contains the response from method BlobInventoryPoliciesClient.NewListPager.
type BlobInventoryPoliciesClientListResponse struct {
// List of blob inventory policies returned.
	ListBlobInventoryPolicy
}

// DeletedAccountsClientGetResponse contains the response from method DeletedAccountsClient.Get.
type DeletedAccountsClientGetResponse struct {
// Deleted storage account
	DeletedAccount
}

// DeletedAccountsClientListResponse contains the response from method DeletedAccountsClient.NewListPager.
type DeletedAccountsClientListResponse struct {
// The response from the List Deleted Accounts operation.
	DeletedAccountListResult
}

// EncryptionScopesClientGetResponse contains the response from method EncryptionScopesClient.Get.
type EncryptionScopesClientGetResponse struct {
// The Encryption Scope resource.
	EncryptionScope
}

// EncryptionScopesClientListResponse contains the response from method EncryptionScopesClient.NewListPager.
type EncryptionScopesClientListResponse struct {
// List of encryption scopes requested, and if paging is required, a URL to the next page of encryption scopes.
	EncryptionScopeListResult
}

// EncryptionScopesClientPatchResponse contains the response from method EncryptionScopesClient.Patch.
type EncryptionScopesClientPatchResponse struct {
// The Encryption Scope resource.
	EncryptionScope
}

// EncryptionScopesClientPutResponse contains the response from method EncryptionScopesClient.Put.
type EncryptionScopesClientPutResponse struct {
// The Encryption Scope resource.
	EncryptionScope
}

// LocalUsersClientCreateOrUpdateResponse contains the response from method LocalUsersClient.CreateOrUpdate.
type LocalUsersClientCreateOrUpdateResponse struct {
// The local user associated with the storage accounts.
	LocalUser
}

// LocalUsersClientDeleteResponse contains the response from method LocalUsersClient.Delete.
type LocalUsersClientDeleteResponse struct {
	// placeholder for future response values
}

// LocalUsersClientGetResponse contains the response from method LocalUsersClient.Get.
type LocalUsersClientGetResponse struct {
// The local user associated with the storage accounts.
	LocalUser
}

// LocalUsersClientListKeysResponse contains the response from method LocalUsersClient.ListKeys.
type LocalUsersClientListKeysResponse struct {
// The Storage Account Local User keys.
	LocalUserKeys
}

// LocalUsersClientListResponse contains the response from method LocalUsersClient.NewListPager.
type LocalUsersClientListResponse struct {
// List of local users requested, and if paging is required, a URL to the next page of local users.
	LocalUsers
}

// LocalUsersClientRegeneratePasswordResponse contains the response from method LocalUsersClient.RegeneratePassword.
type LocalUsersClientRegeneratePasswordResponse struct {
// The secrets of Storage Account Local User.
	LocalUserRegeneratePasswordResult
}

// ManagementPoliciesClientCreateOrUpdateResponse contains the response from method ManagementPoliciesClient.CreateOrUpdate.
type ManagementPoliciesClientCreateOrUpdateResponse struct {
// The Get Storage Account ManagementPolicies operation response.
	ManagementPolicy
}

// ManagementPoliciesClientDeleteResponse contains the response from method ManagementPoliciesClient.Delete.
type ManagementPoliciesClientDeleteResponse struct {
	// placeholder for future response values
}

// ManagementPoliciesClientGetResponse contains the response from method ManagementPoliciesClient.Get.
type ManagementPoliciesClientGetResponse struct {
// The Get Storage Account ManagementPolicies operation response.
	ManagementPolicy
}

// ObjectReplicationPoliciesClientCreateOrUpdateResponse contains the response from method ObjectReplicationPoliciesClient.CreateOrUpdate.
type ObjectReplicationPoliciesClientCreateOrUpdateResponse struct {
// The replication policy between two storage accounts. Multiple rules can be defined in one policy.
	ObjectReplicationPolicy
}

// ObjectReplicationPoliciesClientDeleteResponse contains the response from method ObjectReplicationPoliciesClient.Delete.
type ObjectReplicationPoliciesClientDeleteResponse struct {
	// placeholder for future response values
}

// ObjectReplicationPoliciesClientGetResponse contains the response from method ObjectReplicationPoliciesClient.Get.
type ObjectReplicationPoliciesClientGetResponse struct {
// The replication policy between two storage accounts. Multiple rules can be defined in one policy.
	ObjectReplicationPolicy
}

// ObjectReplicationPoliciesClientListResponse contains the response from method ObjectReplicationPoliciesClient.NewListPager.
type ObjectReplicationPoliciesClientListResponse struct {
// List storage account object replication policies.
	ObjectReplicationPolicies
}

// OperationsClientListResponse contains the response from method OperationsClient.NewListPager.
type OperationsClientListResponse struct {
// Result of the request to list Storage operations. It contains a list of operations and a URL link to get the next set of
// results.
	OperationListResult
}

// PrivateEndpointConnectionsClientDeleteResponse contains the response from method PrivateEndpointConnectionsClient.Delete.
type PrivateEndpointConnectionsClientDeleteResponse struct {
	// placeholder for future response values
}

// PrivateEndpointConnectionsClientGetResponse contains the response from method PrivateEndpointConnectionsClient.Get.
type PrivateEndpointConnectionsClientGetResponse struct {
// The Private Endpoint Connection resource.
	PrivateEndpointConnection
}

// PrivateEndpointConnectionsClientListResponse contains the response from method PrivateEndpointConnectionsClient.NewListPager.
type PrivateEndpointConnectionsClientListResponse struct {
// List of private endpoint connection associated with the specified storage account
	PrivateEndpointConnectionListResult
}

// PrivateEndpointConnectionsClientPutResponse contains the response from method PrivateEndpointConnectionsClient.Put.
type PrivateEndpointConnectionsClientPutResponse struct {
// The Private Endpoint Connection resource.
	PrivateEndpointConnection
}

// PrivateLinkResourcesClientListByStorageAccountResponse contains the response from method PrivateLinkResourcesClient.ListByStorageAccount.
type PrivateLinkResourcesClientListByStorageAccountResponse struct {
// A list of private link resources
	PrivateLinkResourceListResult
}

// SKUsClientListResponse contains the response from method SKUsClient.NewListPager.
type SKUsClientListResponse struct {
// The response from the List Storage SKUs operation.
	SKUListResult
}

// UsagesClientListByLocationResponse contains the response from method UsagesClient.NewListByLocationPager.
type UsagesClientListByLocationResponse struct {
// The response from the List Usages operation.
	UsageListResult
}

